//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing_T {
	
	
	public partial class auth_edit_new {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label Label6;
		
		protected System.Web.UI.WebControls.TextBox InputID;
		
		protected System.Web.UI.WebControls.Label Msg_ExistID;
		
		protected System.Web.UI.WebControls.Label Label11;
		
		protected System.Web.UI.WebControls.TextBox InputName;
		
		protected System.Web.UI.WebControls.Label Label13;
		
		protected System.Web.UI.WebControls.Button Button3;
	}
}
