//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing_T {
	
	
	public partial class auth_edit {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HiddenField HiddenF_ActionState;
		
		protected System.Web.UI.WebControls.HiddenField HiddenF_rid;
		
		protected System.Web.UI.WebControls.Label a_id;
		
		protected System.Web.UI.WebControls.TextBox auth_name_input;
		
		protected System.Web.UI.WebControls.Button btUpDate;
		
		protected System.Web.UI.WebControls.Button btDelete;
	}
}
