//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing_T {
	
	
	public partial class company_edit {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label com_id;
		
		protected System.Web.UI.WebControls.TextBox com_name;
		
		protected System.Web.UI.WebControls.TextBox com_address;
		
		protected System.Web.UI.WebControls.TextBox com_un;
		
		protected System.Web.UI.WebControls.TextBox com_agent;
		
		protected System.Web.UI.WebControls.TextBox com_tel;
		
		protected System.Web.UI.WebControls.TextBox com_fax;
		
		protected System.Web.UI.WebControls.Label Label2;
		
		protected System.Web.UI.WebControls.Button btnUpdatecompany;
	}
}
