//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing_T {
	
	
	public partial class group_edit {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HiddenField HiddenF_ActionState;
		
		protected System.Web.UI.WebControls.HiddenField HiddenF_rid;
		
		protected System.Web.UI.WebControls.Label r_id;
		
		protected System.Web.UI.WebControls.TextBox TextBox1;
		
		protected System.Web.UI.WebControls.Button btnUpdate;
		
		protected System.Web.UI.WebControls.Button btnDelete;
	}
}
