//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoicing_T {
	
	
	public partial class login {
		
		protected System.Web.UI.HtmlControls.HtmlForm loginform;
		
		protected System.Web.UI.WebControls.TextBox InputAccount;
		
		protected System.Web.UI.WebControls.TextBox InputPassword;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_error;
		
		protected System.Web.UI.WebControls.Label msg_error;
	}
}
